//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimsDetectionAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_Subscribers
    {
        public int SubscriberID { get; set; }
        public string SubscriberName { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
