//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimsDetectionAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SubscriberDBContext : DbContext
    {
        public SubscriberDBContext()
            : base("name=SubscriberDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ref_ClaimStatus> ref_ClaimStatus { get; set; }
        public virtual DbSet<ref_Customer> ref_Customer { get; set; }
        public virtual DbSet<ref_InsuranceCompany> ref_InsuranceCompany { get; set; }
        public virtual DbSet<ref_Subscribers> ref_Subscribers { get; set; }
        public virtual DbSet<trn_Claim> trn_Claim { get; set; }
        public virtual DbSet<trn_Policy> trn_Policy { get; set; }
    }
}
