//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimsDetectionAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trn_Policy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trn_Policy()
        {
            this.trn_Claim = new HashSet<trn_Claim>();
        }
    
        public int PolicyID { get; set; }
        public int CustomerId { get; set; }
        public string PolicyName { get; set; }
        public string PolicyType { get; set; }
        public string PolicyReferenceNumber { get; set; }
        public string PolicyDetails { get; set; }
        public System.DateTime PolictStartDate { get; set; }
        public System.DateTime PolictEndDate { get; set; }
        public int CompanyID { get; set; }
    
        public virtual ref_Customer ref_Customer { get; set; }
        public virtual ref_InsuranceCompany ref_InsuranceCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_Claim> trn_Claim { get; set; }
    }
}
